development: &development
  host: 'http://localhost:8080'
  namespace: ''

test: &test
  host: 'http://ec2-75-101-164-22.compute-1.amazonaws.com'
  namespace: ''

cucumber:
  <<: *test

production:
  host: 'http://ec2-75-101-164-22.compute-1.amazonaws.com'
  namespace: ''
  

